version: '3'

services:
  servers:
    build: ./server
    depends_on: 
      - mongodb
    ports:
      - '3000:3000'
    networks:
      - host

  mongodb:
    image: mongo
    healthcheck:
      test:
      - CMD
      - mongo
      - eval
      - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    networks:
      - host

  client:
    build: ./client
    ports:
      - "8000:8000"
    networks:
      - host

networks:
  host:

  
